"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

export type Language = "en" | "no" | "ur" | "so" | "ti" | "ar" | "hi"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Header
    appTitle: "FleetTracker Pro",
    appSubtitle: "Modern Fleet Management",
    addVehicle: "Add Vehicle",
    refreshing: "Refreshing...",
    daysAgo: "days ago",

    // Navigation
    filters: "Filters",
    search: "Search by plate, model, location, or driver...",
    showingResults: "Showing",
    of: "of",
    lastUpdated: "Last updated:",
    clearSearch: "Clear search",

    // Stats
    totalFleet: "Total Fleet",
    inUse: "In Use",
    reserved: "Reserved",
    maintenance: "Maintenance",
    utilization: "Utilization",
    lowBatteryAlert: "Low Battery Alert",
    lowChargeAlert: "Low Charge Alert",
    needCharging: "need charging",
    needRecharging: "need recharging",
    thisMonth: "this month",
    highUsage: "High usage",
    mediumUsage: "Medium usage",
    lowUsage: "Low usage",

    // Filters
    allStatus: "All Status",
    allLocations: "All Locations",
    allLevels: "All Levels",
    status: "Status",
    location: "Location",
    batteryLevel: "Battery Level",
    chargeLevel: "Charge Level",
    high: "High (70%+)",
    medium: "Medium (30-70%)",
    low: "Low (<30%)",

    // Car Status
    free: "Available",
    busy: "In Use",
    inTransit: "In Transit",
    availableAtLastLocation: "Available at Last Location",
    scheduledService: "Scheduled service",

    // Actions
    take: "Take",
    return: "Return",
    reserve: "Reserve",
    manage: "Manage",
    startTrip: "Start Trip",
    cancel: "Cancel",
    close: "Close",
    loading: "Loading...",
    takeCar: "Take Car",
    returnCar: "Return Car",
    takeVehicle: "Take Vehicle",
    returnVehicle: "Return Vehicle",
    cancelReservation: "Cancel Reservation",
    setInUse: "Set In Use",
    setMaintenance: "Set Maintenance",

    // Time
    justNow: "Just now",
    minutesAgo: "minutes ago",
    hoursAgo: "hours ago",
    ago: "ago",

    // Vehicle Details
    vehicleDetails: "Vehicle Details",
    currentlyAt: "Currently at:",
    mileage: "Mileage",
    miles: "miles",
    battery: "Battery",
    charge: "Charge",
    vehicleStatus: "Vehicle Status",
    vehicleNotes: "Vehicle Notes",
    addNotes: "Add notes about vehicle condition, issues, maintenance needs, etc.",

    // Current Assignment
    currentlyInUse: "Currently In Use",
    reservedBy: "Reserved by",
    from: "From:",
    scheduledByAdmin: "Scheduled by Admin",

    // Admin Dashboard
    adminDashboard: "Admin Dashboard",
    adminDashboardDescription: "Komplett flåtestyring og overvåking",
    completeFleetControl: "Komplett Flåtekontroll",
    refresh: "Oppdater",
    saveChanges: "Lagre Endringer",
    totalVehicles: "Totale Kjøretøy",
    totalPhotos: "Totale Bilder",
    pickupPhotos: "Hentebilder",
    returnPhotos: "Returbilder",
    activeDrivers: "Aktive Sjåfører",
    weeklyTrips: "Ukentlige Turer",
    weeklyRevenue: "Ukentlig Inntekt",
    fleetManagement: "Flåtestyring",
    reports: "Rapporter",
    drivers: "Sjåfører",
    settings: "Innstillinger",
    searchVehicles: "Søk kjøretøy...",
    filterByStatus: "Filter by status",
    allStatuses: "Alle Statuser",
    addVehicle: "Legg til Kjøretøy",
    addCar: "Legg til Bil",
    deleteVehicle: "Slett Kjøretøy",
    deleteVehicleConfirm: "Er du sikker på at du vil slette",
    delete: "Slett",
    editVehicle: "Rediger Kjøretøy",
    editCar: "Rediger Bil",
    addNewVehicle: "Legg til Nytt Kjøretøy",
    addNewCar: "Legg til Ny Bil",
    initialLocation: "Opprinnelig Plassering",
    weeklyReports: "Ukentlige Rapporter",
    generateReport: "Generer Rapport",
    generating: "Genererer...",
    downloadVakliste: "Last ned Vakliste",
    week: "Uke",
    totalTrips: "Totale Turer",
    totalRevenue: "Total Inntekt",
    driverPerformance: "Sjåførytelse",
    driverManagement: "Sjåføradministrasjon",
    driverManagementComingSoon: "Sjåføradministrasjonsfunksjoner kommer snart",
    systemSettings: "Systeminnstillinger",
    maintenanceThreshold: "Vedlikeholdsterskel (km)",
    fuelAlertThreshold: "Drivstoffvarsel Terskel (%)",
    autoMaintenanceAlerts: "Automatiske Vedlikeholdsvarsler",
    autoMaintenanceDescription: "Varsle automatisk når kjøretøy trenger vedlikehold basert på kilometer eller tid",
    configure: "Konfigurer",
    vaktliste: "Vaktliste",
    addDriver: "Legg til Sjåfør",
    addNewDriver: "Legg til Ny Sjåfør",
    driverName: "Sjåførsnavn",
    phoneNumber: "Telefonnummer",
    licenseNumber: "Førerkortnummer",
    email: "E-post",
    deleteDriver: "Slett Sjåfør",
    deleteDriverConfirm: "Er du sikker på at du vil slette",
    addShift: "Legg til Vakt",
    previousWeek: "Forrige Uke",
    nextWeek: "Neste Uke",
    weekSchedule: "Ukentlig Timeplan",
    noShifts: "Ingen vakter planlagt",
    editDriver: "Rediger Sjåfør",
    driver: "Sjåfør",
    selectDriver: "Velg Sjåfør",
    date: "Dato",
    startTime: "Starttid",
    endTime: "Sluttid",
    vehicle: "Kjøretøy",
    selectVehicle: "Velg Kjøretøy",
    notes: "Notater",
    optionalNotes: "Optional notes",
    status: "Status",
    plateNumber: "Skiltnummer",
    model: "Modell",
    location: "Plassering",
    battery: "Batteri",
    mileage: "Kilometerstand",
    lastUpdated: "Sist oppdatert",
    viewPhotos: "Se Bilder",
    photos: "Bilder",
    recentPhotos: "Nylige Bilder",
    noPhotosYet: "Ingen bilder ennå",
    noPhotosDescription: "Bilder vil vises her når de lastes opp",
    scheduleCar: "Planlegg Bil",
    schedule: "Planlegg",
    from: "Fra",
    to: "Til",
    save: "Lagre",
    cancel: "Avbryt",
    success: "Suksess",
    error: "Feil",
    fleet: "Flåte",
    viewSchedule: {
      en: "View Schedule",
      no: "Se Timeplan"
    },
    sendSchedule: {
      en: "Send Schedule",
      no: "Send Timeplan"
    },
    driverSchedule: {
      en: "Driver Schedule",
      no: "Sjåfør Timeplan"
    },
    scheduleFor: {
      en: "Schedule for",
      no: "Timeplan for"
    },
    totalHours: {
      en: "Total Hours",
      no: "Totale Timer"
    },
    averageHours: {
      en: "Average Hours/Day",
      no: "Gjennomsnitt Timer/Dag"
    },
    sendVia: {
      en: "Send via",
      no: "Send via"
    },
    sms: {
      en: "SMS",
      no: "SMS"
    },
    email: {
      en: "Email",
      no: "E-post"
    },
    pushNotification: {
      en: "Push Notification",
      no: "Push Varsel"
    },
    scheduleSent: {
      en: "Schedule sent successfully!",
      no: "Timeplan sendt!"
    },
    customizeMessage: {
      en: "Customize Message",
      no: "Tilpass Melding"
    },
    previewMessage: {
      en: "Preview Message",
      no: "Forhåndsvis Melding"
    },
    refreshing: "Oppdaterer...",
    driverAuthentication: "Sjåførautentisering",
    pleaseEnterDriverDetails: "Vennligst fyll ut sjåføropplysninger for å fortsette",
    driverId: "Sjåfør ID",
    enterDriverId: "Skriv inn sjåfør ID (1234)",
    driverName: "Sjåførnavn",
    enterDriverName: "Skriv inn sjåførnavn (Bruker 1-10)",
    validating: "Validerer...",
    authenticateDriver: "Autentiser Sjåfør",
  },

  no: {
    // Header
    appTitle: "FleetTracker Pro",
    appSubtitle: "Moderne Elbil Flåtestyring",
    addVehicle: "Legg til Kjøretøy",

    // Navigation
    filters: "Filtre",
    search: "Søk etter skilt, modell, sted eller sjåfør...",
    showingResults: "Viser",
    of: "av",
    lastUpdated: "Sist oppdatert:",
    clearSearch: "Tøm søk",

    // Stats
    totalFleet: "Total Flåte",
    available: "Tilgjengelig",
    inUse: "I Bruk",
    reserved: "Reservert",
    maintenance: "Vedlikehold",
    utilization: "Utnyttelse",
    lowBatteryAlert: "Lavt Batteri Varsel",
    lowChargeAlert: "Lav Lading Varsel",
    needCharging: "trenger lading",
    needRecharging: "trenger lading",
    vehicles: "kjøretøy",
    vehicle: "kjøretøy",
    thisMonth: "denne måneden",
    highUsage: "Høy bruk",
    mediumUsage: "Middels bruk",
    lowUsage: "Lav bruk",

    // Filters
    allStatus: "Alle Statuser",
    allLocations: "Alle Steder",
    allLevels: "Alle Nivåer",
    status: "Status",
    location: "Sted",
    batteryLevel: "Batterinivå",
    chargeLevel: "Ladenivå",
    high: "Høy (70%+)",
    medium: "Middels (30-70%)",
    low: "Lav (<30%)",

    // Car Status
    free: "Tilgjengelig",
    busy: "I Bruk",
    inTransit: "På Vei",
    availableAtLastLocation: "Tilgjengelig på Siste Sted",
    scheduledService: "Planlagt service",

    // Actions
    take: "Ta",
    return: "Returner",
    reserve: "Reserver",
    manage: "Administrer",
    startTrip: "Start Tur",
    cancel: "Avbryt",
    close: "Lukk",
    loading: "Laster...",
    takeCar: "Ta Bil",
    returnCar: "Returner Bil",
    takeVehicle: "Ta Kjøretøy",
    returnVehicle: "Returner Kjøretøy",
    cancelReservation: "Avbryt Reservasjon",
    setInUse: "Sett I Bruk",
    setMaintenance: "Sett Vedlikehold",
    setAvailable: "Sett Tilgjengelig",
    deleteSelected: "Slett Valgte",
    noPhotosFound: "Ingen bilder funnet",

    // Time
    justNow: "Akkurat nå",
    minutesAgo: "minutter siden",
    hoursAgo: "timer siden",
    ago: "siden",

    // Vehicle Details
    vehicleDetails: "Kjøretøydetaljer",
    currentlyAt: "For øyeblikket på:",
    mileage: "Kjørelengde",
    miles: "km",
    battery: "Batteri",
    charge: "Lading",
    vehicleStatus: "Kjøretøystatus",
    vehicleNotes: "Kjøretøynotater",
    addNotes: "Legg til notater om kjøretøytilstand, problemer, vedlikeholdsbehov, etc.",

    // Current Assignment
    currentlyInUse: "For Øyeblikket I Bruk",
    reservedBy: "Reservert av",
    from: "Fra:",
    until: "Til:",
    scheduledByAdmin: "Planlagt av Admin",

    // Reservation
    reserveCar: "Reserver",
    confirmReservation: "Bekreft Reservasjon",
    reservationDetails: "Reservasjonsdetaljer",
    phoneNumber: "Telefonnummer",
    driverName: "Sjåførnavn",
    reservationDate: "Reservasjonsdato",
    startTime: "Starttid",
    deliveryTime: "Leveringstid (Valgfritt)",
    expectedDuration: "Forventet Varighet",
    notes: "Notater (Valgfritt)",
    reservationSummary: "Reservasjonsoversikt",
    multipleReservations: "Flere Reservasjoner",
    addAnotherReservation: "Legg til Ny Reservasjon",
    start: "Start",
    end: "Slutt",
    duration: "Varighet",
    driver: "Sjåfør",
    notSpecified: "Ikke spesifisert",

    // Photos
    beforePhoto: "Før Bilde (Henting)",
    afterPhoto: "Etter Levering",
    uploadPhoto: "Last opp Bilde",
    takePhoto: "Ta Bilde",
    chooseFile: "Velg Fil",
    remove: "Fjern",
    replace: "Erstatt",
    uploadBefore: "Last opp før bilde",
    uploadAfter: "Last opp etter bilde",
    takePhotoBefore: "Ta et bilde når du henter kjøretøyet",
    takePhotoAfter: "Ta et bilde når du returnerer kjøretøyet",
    overview: "Oversikt",
    photos: "Bilder",
    actions: "Handlinger",

    // Photo Capture
    photoCapturePickup: "Fotoopptak - Henting",
    photoCaptureReturn: "Fotoopptak - Levering",
    photoCaptureInstructions: "Ta 4 bilder av kjøretøyet: foran, bak, høyre, og venstre side",
    progress: "Fremgang",
    currentPosition: "Nåværende posisjon",
    positionInstructions: "Stil kamera på riktig sted for å ta bildet",
    ofVehicle: "av kjøretøyet",
    capturing: "Tar opp bilder",
    capture: "Ta bilde",
    captured: "Bilde tatt",
    completePhotoCapture: "Fullfør fotoopptak",
    previous: "Forrige",
    next: "Neste",
    front: "Foran",
    back: "Bak",
    right: "Høyre",
    left: "Venstre",

    // Form validation
    required: "Påkrevd",
    phoneNumberRequired: "Telefonnummer er påkrevd",
    driverNameRequired: "Sjåførnavn er påkrevd",
    dateRequired: "Reservasjonsdato er påkrevd",
    timeRequired: "Reservasjonstid er påkrevd",
    futureRequired: "Reservasjon må være i fremtiden",
    fillAllFields: "Vennligst fyll ut alle påkrevde felt",
    fixErrors: "Vennligst rett følgende feil:",
    overlappingReservations: "Overlappende reservasjoner funnet",

    // Time durations
    "1hour": "1 time",
    "2hours": "2 timer",
    "3hours": "3 timer",
    "4hours": "4 timer (halv skift)",
    "6hours": "6 timer",
    "8hours": "8 timer (full skift)",
    "10hours": "10 timer",
    "12hours": "12 timer (utvidet skift)",
    "24hours": "24 timer (full dag)",
    hour: "time",
    hours: "timer",
    halfShift: "halv skift",
    fullShift: "full skift",
    extendedShift: "utvidet skift",
    fullDay: "full dag",

    // Empty states
    noVehiclesFound: "Ingen kjøretøy funnet",
    tryAdjusting: "Prøv å justere søket eller filtrene",
    noVehiclesAvailable: "Ingen kjøretøy tilgjengelig i flåten din",

    // Camera
    startingCamera: "Starter kamera...",
    couldNotAccess: "Kunne ikke få tilgang til kamera. Sjekk tillatelser.",
    retake: "Ta på nytt",
    usePhoto: "Bruk Bilde",
    startCamera: "Start Kamera",

    // Alerts
    lowBatteryNeeds: "Lavt batteri - trenger lading",
    lowChargeNeeds: "Lav lading - trenger lading",
    quickAssignment: "Rask Tildeling",

    // Admin Dashboard
    adminDashboard: "Admin Dashboard",
    completeFleetControl: "Komplett Flåtekontroll",
    refresh: "Oppdater",
    saveChanges: "Lagre Endringer",
    totalVehicles: "Totale Kjøretøy",
    activeDrivers: "Aktive Sjåfører",
    weeklyTrips: "Ukentlige Turer",
    weeklyRevenue: "Ukentlig Inntekt",
    fleetManagement: "Flåtestyring",
    reports: "Rapporter",
    drivers: "Sjåfører",
    settings: "Innstillinger",
    searchVehicles: "Søk kjøretøy...",
    filterByStatus: "Filtrer etter status",
    allStatuses: "Alle Statuser",
    addCar: "Legg til Bil",
    deleteVehicle: "Slett Kjøretøy",
    deleteVehicleConfirm: "Er du sikker på at du vil slette",
    delete: "Slett",
    editCar: "Rediger Bil",
    addNewCar: "Legg til Ny Bil",
    initialLocation: "Opprinnelig Plassering",
    weeklyReports: "Ukentlige Rapporter",
    generateReport: "Generer Rapport",
    generating: "Genererer...",
    downloadVakliste: "Last ned Vakliste",
    week: "Uke",
    totalTrips: "Totale Turer",
    totalRevenue: "Total Inntekt",
    driverPerformance: "Sjåførytelse",
    driverManagement: "Sjåføradministrasjon",
    driverManagementComingSoon: "Sjåføradministrasjonsfunksjoner kommer snart",
    systemSettings: "Systeminnstillinger",
    maintenanceThreshold: "Vedlikeholdsterskel (km)",
    fuelAlertThreshold: "Drivstoffvarsel Terskel (%)",
    autoMaintenanceAlerts: "Automatiske Vedlikeholdsvarsler",
    autoMaintenanceDescription: "Varsle automatisk når kjøretøy trenger vedlikehold basert på kilometer eller tid",
    configure: "Konfigurer",
    vaktliste: "Vaktliste",
    addDriver: "Legg til Sjåfør",
    addNewDriver: "Legg til Ny Sjåfør",
    licenseNumber: "Førerkortnummer",
    email: "E-post",
    deleteDriver: "Slett Sjåfør",
    deleteDriverConfirm: "Er du sikker på at du vil slette",
    addShift: "Legg til Vakt",
    previousWeek: "Forrige Uke",
    nextWeek: "Neste Uke",
    weekSchedule: "Ukentlig Timeplan",
    noShifts: "Ingen vakter planlagt",
    selectDriver: "Velg Sjåfør",
    date: "Dato",
    startTime: "Starttid",
    endTime: "Sluttid",
    selectVehicle: "Velg Kjøretøy",
    optionalNotes: "Valgfrie notater",
    plateNumber: "Skiltnummer",
    model: "Modell",
    location: "Plassering",
    viewPhotos: "Se Bilder",
    recentPhotos: "Nylige Bilder",
    noPhotosYet: "Ingen bilder ennå",
    noPhotosDescription: "Bilder vil vises her når de lastes opp",
    scheduleCar: "Planlegg Bil",
    schedule: "Planlegg",
    to: "Til",
    save: "Lagre",
    success: "Suksess",
    error: "Feil",
    fleet: "Flåte",
    viewSchedule: {
      en: "View Schedule",
      no: "Se Timeplan"
    },
    sendSchedule: {
      en: "Send Schedule",
      no: "Send Timeplan"
    },
    driverSchedule: {
      en: "Driver Schedule",
      no: "Sjåfør Timeplan"
    },
    scheduleFor: {
      en: "Schedule for",
      no: "Timeplan for"
    },
    totalHours: {
      en: "Total Hours",
      no: "Totale Timer"
    },
    averageHours: {
      en: "Average Hours/Day",
      no: "Gjennomsnitt Timer/Dag"
    },
    sendVia: {
      en: "Send via",
      no: "Send via"
    },
    sms: {
      en: "SMS",
      no: "SMS"
    },
    email: {
      en: "Email",
      no: "E-post"
    },
    pushNotification: {
      en: "Push Notification",
      no: "Push Varsel"
    },
    scheduleSent: {
      en: "Schedule sent successfully!",
      no: "Timeplan sendt!"
    },
    customizeMessage: {
      en: "Customize Message",
      no: "Tilpass Melding"
    },
    previewMessage: {
      en: "Preview Message",
      no: "Forhåndsvis Melding"
    },
    refreshing: "Oppdaterer...",
    driverAuthentication: "Sjåførautentisering",
    pleaseEnterDriverDetails: "Vennligst fyll ut sjåføropplysninger for å fortsette",
    driverId: "Sjåfør ID",
    enterDriverId: "Skriv inn sjåfør ID (1234)",
    enterDriverName: "Skriv inn sjåførnavn (Bruker 1-10)",
    validating: "Validerer...",
    authenticateDriver: "Autentiser Sjåfør",
  },

  ur: {
    // Header
    appTitle: "فلیٹ ٹریکر پرو",
    appSubtitle: "جدید الیکٹرک فلیٹ منیجمنٹ",
    addVehicle: "گاڑی شامل کریں",

    // Navigation
    filters: "فلٹرز",
    search: "پلیٹ، ماڈل، مقام یا ڈرائیور سے تلاش کریں...",
    showingResults: "دکھا رہا ہے",
    of: "میں سے",
    lastUpdated: "آخری بار اپڈیٹ:",
    clearSearch: "تلاش صاف کریں",

    // Stats
    totalFleet: "کل فلیٹ",
    available: "دستیاب",
    inUse: "استعمال میں",
    reserved: "محفوظ",
    maintenance: "مرمت",
    utilization: "استعمال",
    lowBatteryAlert: "کم بیٹری الرٹ",
    lowChargeAlert: "کم چارج الرٹ",
    needCharging: "چارجنگ کی ضرورت",
    needRecharging: "چارجنگ کی ضرورت",
    vehicles: "گاڑیاں",
    vehicle: "گاڑی",
    thisMonth: "اس مہینے",
    highUsage: "زیادہ استعمال",
    mediumUsage: "درمیانہ استعمال",
    lowUsage: "کم استعمال",

    // Filters
    allStatus: "تمام حالات",
    allLocations: "تمام مقامات",
    allLevels: "تمام سطحیں",
    status: "حالت",
    location: "مقام",
    batteryLevel: "بیٹری کی سطح",
    chargeLevel: "چارج کی سطح",
    high: "زیادہ (70%+)",
    medium: "درمیانہ (30-70%)",
    low: "کم (<30%)",

    // Car Status
    free: "دستیاب",
    busy: "استعمال میں",
    inTransit: "راستے میں",
    availableAtLastLocation: "آخری جگہ دستیاب",
    scheduledService: "طے شدہ سروس",

    // Actions
    take: "لیں",
    return: "واپس",
    reserve: "محفوظ کریں",
    manage: "منظم کریں",
    startTrip: "سفر شروع",
    cancel: "منسوخ",
    close: "بند",
    takeCar: "گاڑی لیں",
    returnCar: "گاڑی واپس کریں",
    takeVehicle: "گاڑی لیں",
    returnVehicle: "گاڑی واپس کریں",
    cancelReservation: "ریزرویشن منسوخ کریں",
    setInUse: "میں استعمال کردہ",
    setMaintenance: "مرمت کردہ",

    // Time
    justNow: "ابھی",
    minutesAgo: "منٹ پہلے",
    hoursAgo: "گھنٹے پہلے",
    ago: "پہلے",

    // Vehicle Details
    vehicleDetails: "گاڑی کی تفصیلات",
    currentlyAt: "فی الوقت:",
    mileage: "مائلیج",
    miles: "کلومیٹر",
    battery: "بیٹری",
    charge: "چارج",
    vehicleStatus: "گاڑی کی حالت",
    vehicleNotes: "گاڑی کے نوٹس",
    addNotes: "گاڑی کی حالت، مسائل، مرمت کی ضروریات وغیرہ کے بارے میں نوٹس شامل کریں۔",

    // Current Assignment
    currentlyInUse: "فی الوقت استعمال میں",
    reservedBy: "محفوظ کردہ",
    from: "سے:",
    until: "تک:",
    scheduledByAdmin: "پلان کے لئے ایڈمن",

    // Reservation
    reserveCar: "محفوظ کریں",
    confirmReservation: "ریزرویشن کی تصدیق",
    reservationDetails: "ریزرویشن کی تفصیلات",
    phoneNumber: "فون نمبر",
    driverName: "ڈرائیور کا نام",
    reservationDate: "ریزرویشن کی تاریخ",
    startTime: "شروع کا وقت",
    deliveryTime: "ڈیلیوری کا وقت (اختیاری)",
    expectedDuration: "متوقع مدت",
    notes: "نوٹس (اختیاری)",
    reservationSummary: "ریزرویشن کا خلاصہ",
    multipleReservations: "متعدد ریزرویشن",
    addAnotherReservation: "نیا ریزرویشن شامل کریں",
    start: "شروع",
    end: "اختتام",
    duration: "مدت",
    driver: "ڈرائیور",
    notSpecified: "مخصوص نہیں",

    // Photos
    beforePhoto: "پہلے کی تصویر (اٹھانا)",
    afterPhoto: "ڈیلیوری کے بعد",
    uploadPhoto: "تصویر اپ لوڈ کریں",
    takePhoto: "تصویر لیں",
    chooseFile: "فائل منتخب کریں",
    remove: "ہٹائیں",
    replace: "تبدیل کریں",
    uploadBefore: "پہلے کی تصویر اپ لوڈ کریں",
    uploadAfter: "بعد کی تصویر اپ لوڈ کریں",
    takePhotoBefore: "گاڑی لیتے وقت تصویر لیں",
    takePhotoAfter: "گاڑی واپس کرتے وقت تصویر لیں",
    overview: "جائزہ",
    photos: "تصاویر",
    actions: "اعمال",

    // Photo Capture
    photoCapturePickup: "فوٹوپیک - اٹھانا",
    photoCaptureReturn: "فوٹوپیک - واپس",
    photoCaptureInstructions: "گاڑی کے چار طرف کی تصاویر لیں: پیچھا, بھیڑا, دیگرا اور بائیں طرف",
    progress: "پیروی",
    currentPosition: "نوں وقت کی جگہ",
    positionInstructions: "کیمرہ کو چار طرف کی جگہ پر جگہ لگائیں",
    ofVehicle: "گاڑی کے لئے",
    capturing: "فوٹوپیک",
    capture: "فوٹوپیک",
    captured: "فوٹوپیک",
    completePhotoCapture: "فوٹوپیک بھر پورا",
    previous: "پچھا",
    next: "پیچھا",
    front: "پیچھا",
    back: "بھیڑا",
    right: "دیگرا",
    left: "بائیں",

    // Form validation
    required: "ضروری",
    phoneNumberRequired: "فون نمبر ضروری ہے",
    driverNameRequired: "ڈرائیور کا نام ضروری ہے",
    dateRequired: "ریزرویشن کی تاریخ ضروری ہے",
    timeRequired: "ریزرویشن کا وقت ضروری ہے",
    futureRequired: "ریزرویشن مستقبل میں ہونا چاہیے",
    fillAllFields: "براہ کرم تمام ضروری فیلڈز بھریں",
    fixErrors: "براہ کرم مندرجہ ذیل خرابیاں ٹھیک کریں:",
    overlappingReservations: "اوور لیپنگ ریزرویشن ملے",

    // Time durations
    "1hour": "1 گھنٹہ",
    "2hours": "2 گھنٹے",
    "3hours": "3 گھنٹے",
    "4hours": "4 گھنٹے (آدھی شفٹ)",
    "6hours": "6 گھنٹے",
    "8hours": "8 گھنٹے (مکمل شفٹ)",
    "10hours": "10 گھنٹے",
    "12hours": "12 گھنٹے (توسیعی شفٹ)",
    "24hours": "24 گھنٹے (پورا دن)",
    hour: "گھنٹہ",
    hours: "گھنٹے",
    halfShift: "آدھی شفٹ",
    fullShift: "مکمل شفٹ",
    extendedShift: "توسیعی شفٹ",
    fullDay: "پورا دن",

    // Empty states
    noVehiclesFound: "کوئی گاڑی نہیں ملی",
    tryAdjusting: "اپنی تلاش یا فلٹرز کو ایڈجسٹ کرنے کی کوشش کریں",
    noVehiclesAvailable: "آپ کے فلیٹ میں کوئی گاڑی دستیاب نہیں",

    // Camera
    startingCamera: "کیمرہ شروع کر رہا ہے...",
    couldNotAccess: "کیمرہ تک رسائی نہیں ہو سکی۔ اجازات چیک کریں۔",
    retake: "دوبارہ لیں",
    usePhoto: "تصویر استعمال کریں",
    startCamera: "کیمرہ شروع کریں",

    // Alerts
    lowBatteryNeeds: "کم بیٹری - چارجنگ کی ضرورت",
    lowChargeNeeds: "کم چارج - چارجنگ کی ضرورت",
    quickAssignment: "فوری تفویض",

    viewSchedule: {
      en: "View Schedule",
      no: "Se Timeplan"
    },
    sendSchedule: {
      en: "Send Schedule",
      no: "Send Timeplan"
    },
    driverSchedule: {
      en: "Driver Schedule",
      no: "Sjåfør Timeplan"
    },
    scheduleFor: {
      en: "Schedule for",
      no: "Timeplan for"
    },
    totalHours: {
      en: "Total Hours",
      no: "Totale Timer"
    },
    averageHours: {
      en: "Average Hours/Day",
      no: "Gjennomsnitt Timer/Dag"
    },
    sendVia: {
      en: "Send via",
      no: "Send via"
    },
    sms: {
      en: "SMS",
      no: "SMS"
    },
    email: {
      en: "Email",
      no: "E-post"
    },
    pushNotification: {
      en: "Push Notification",
      no: "Push Varsel"
    },
    scheduleSent: {
      en: "Schedule sent successfully!",
      no: "Timeplan sendt!"
    },
    customizeMessage: {
      en: "Customize Message",
      no: "Tilpass Melding"
    },
    previewMessage: {
      en: "Preview Message",
      no: "Forhåndsvis Melding"
    },
    refresh: "Oppdater",
    refreshing: "Oppdaterer...",
    driverAuthentication: "Sjåførautentisering",
    pleaseEnterDriverDetails: "Vennligst fyll ut sjåføropplysninger for å fortsette",
    driverId: "Sjåfør ID",
    enterDriverId: "Skriv inn sjåfør ID (1234)",
    driverName: "Sjåførnavn",
    enterDriverName: "Skriv inn sjåførnavn (Bruker 1-10)",
    validating: "Validerer...",
    authenticateDriver: "Autentiser Sjåfør",
  },

  // Add similar comprehensive translations for so, ti, ar, hi...
  // (I'll include a few key ones to show the pattern)

  so: {
    appTitle: "FleetTracker Pro",
    appSubtitle: "Maamulka Gaadiidka Koronto Casriga ah",
    phoneNumber: "Lambarka Telefoonka",
    phoneNumberRequired: "Lambarka telefoonka ayaa loo baahan yahay",
    showingResults: "Muujinaya natiijooyinka",
    of: "ee",
    lastUpdated: "Waqtigii ugu dambeeyay ee la cusbooneysiiyay:",
    clearSearch: "Tirtir raadinta",
    totalFleet: "Wadarta Guud ee Gaadiidka",
    available: "La heli karo",
    inUse: "La isticmaalayo",
    reserved: "La qabsaday",
    maintenance: "Dayactir",
    utilization: "Isticmaal",
    lowBatteryAlert: "Digniin Batariga Yar",
    lowChargeAlert: "Digniin Koronto Yar",
    needCharging: "Wuxuu u baahan yahay in la dallaco",
    needRecharging: "Wuxuu u baahan yahay in la dallaco",
    vehicles: "Gaadiidka",
    vehicle: "Gaadhi",
    thisMonth: "Bishan",
    highUsage: "Isticmaal badan",
    mediumUsage: "Isticmaal dhexdhexaad ah",
    lowUsage: "Isticmaal yar",
    allStatus: "Dhammaan Xaaladaha",
    allLocations: "Dhammaan Goobaha",
    allLevels: "Dhammaan Heerarka",
    status: "Xaalad",
    location: "Goobta",
    batteryLevel: "Heerka Batariga",
    chargeLevel: "Heerka Koronto",
    high: "Sare (70%+)",
    medium: "Dhexdhexaad (30-70%)",
    low: "Hoose (<30%)",
    free: "Bilaash",
    busy: "Mashquul",
    inTransit: "Socdaal ku jira",
    availableAtLastLocation: "Waxaa laga heli karaa goobtii ugu dambeysay",
    scheduledService: "Adeeg loo qorsheeyay",
    take: "Qaado",
    return: "Soo celi",
    reserve: "Kaydi",
    manage: "Maamul",
    startTrip: "Bilow Safar",
    cancel: "Jooji",
    close: "Xir",
    takeCar: "Qaado Gaadhi",
    returnCar: "Soo celi Gaadhi",
    takeVehicle: "Qaado Gaadhi",
    returnVehicle: "Soo celi Gaadhi",
    cancelReservation: "Jooji Kaydinta",
    setInUse: "Sett I Bruk",
    setMaintenance: "Sett Vedlikehold",
    setAvailable: "Sett Tilgjengelig",
    deleteSelected: "Slett Valgte",
    noPhotosFound: "Ingen bilder funnet",
    justNow: "Hadda",
    minutesAgo: "Daqiiqado ka hor",
    hoursAgo: "Saacado ka hor",
    ago: "Ka hor",
    vehicleDetails: "Faahfaahinta Gaadhiga",
    currentlyAt: "Hadda jooga:",
    mileage: "Masaafo",
    miles: "Kiiloomitir",
    battery: "Batariga",
    charge: "Koronto",
    vehicleStatus: "Xaaladda Gaadhiga",
    vehicleNotes: "Qoraallada Gaadhiga",
    addNotes: "Ku dar qoraallo ku saabsan xaaladda gaadhiga, arrimaha, baahiyaha dayactirka, iwm.",
    currentlyInUse: "Hadda La Isticmaalayo",
    reservedBy: "Waxaa qabsaday",
    from: "Laga bilaabo:",
    until: "Ilaa:",
    scheduledByAdmin: "Qaadashada ah",
    reserveCar: "Kaydi Gaadhi",
    confirmReservation: "Xaqiiji Kaydinta",
    reservationDetails: "Faahfaahinta Kaydinta",
    driverName: "Magaca Darawalka",
    reservationDate: "Taariikhda Kaydinta",
    startTime: "Waqtiga Bilowga",
    deliveryTime: "Waqtiga Gaarsiinta (Ikhtiyaari)",
    expectedDuration: "Muddada la filayo",
    notes: "Qoraallo (Ikhtiyaari)",
    reservationSummary: "Soo Koobidda Kaydinta",
    multipleReservations: "Kaydinno Badan",
    addAnotherReservation: "Ku dar Kaydin Kale",
    start: "Bilow",
    end: "Dhammaad",
    duration: "Muddada",
    driver: "Darawal",
    notSpecified: "Lama cayimin",
    beforePhoto: "Sawirka Hore (Qaadashada)",
    afterPhoto: "Ka dib Gaarsiinta",
    uploadPhoto: "Soo rar Sawir",
    takePhoto: "Qaado Sawir",
    chooseFile: "Dooro Fayl",
    remove: "Ka saar",
    replace: "Beddel",
    uploadBefore: "Soo rar sawirka hore",
    uploadAfter: "Soo rar sawirka dambe",
    takePhotoBefore: "Qaado sawir markaad gaadhiga qaadanayso",
    takePhotoAfter: "Qaado sawir markaad gaadhiga soo celinayso",
    overview: "Guudmarka",
    photos: "Sawirro",
    actions: "Tallaabooyin",
    required: "Loo baahan yahay",
    driverNameRequired: "Magaca darawalka ayaa loo baahan yahay",
    dateRequired: "Taariikhda kaydinta ayaa loo baahan yahay",
    timeRequired: "Waqtiga kaydinta ayaa loo baahan yahay",
    futureRequired: "Kaydinta waa inay mustaqbalka ku ahaataa",
    fillAllFields: "Fadlan buuxi dhammaan meelaha loo baahan yahay",
    fixErrors: "Fadlan sax khaladaadka soo socda:",
    overlappingReservations: "Kaydinno is dulsaaran ayaa la helay",
    "1hour": "1 saac",
    "2hours": "2 saacadood",
    "3hours": "3 saacadood",
    "4hours": "4 saacadood (nus wareeg)",
    "6hours": "6 saacadood",
    "8hours": "8 saacadood (wareeg buuxa)",
    "10hours": "10 saacadood",
    "12hours": "12 saacadood (wareeg dheer)",
    "24hours": "24 saacadood (maalin buuxa)",
    hour: "Saac",
    hours: "Saacado",
    halfShift: "Nus wareeg",
    fullShift: "Wareeg buuxa",
    extendedShift: "Wareeg dheer",
    fullDay: "Maalin buuxda",
    noVehiclesFound: "Lama helin wax gaadhi ah",
    tryAdjusting: "Isku day inaad hagaajiso raadintaada ama shaandhayntaada",
    noVehiclesAvailable: "Ma jiro wax gaadhi ah oo laga heli karo gaadiidkaaga",
    startingCamera: "Kamerada ayaa bilaabaneysa...",
    couldNotAccess: "Lama geli karo kamarada. Fadlan hubi rukhsadaha.",
    retake: "Dib u qaad",
    usePhoto: "Isticmaal Sawir",
    startCamera: "Bilow Kamerada",
    lowBatteryNeeds: "Batariga ayaa yaraaday - wuxuu u baahan yahay in la dallaco",
    lowChargeNeeds: "Koronto ayaa yaraaday - wuxuu u baahan yahay in la dallaco",
    quickAssignment: "Qabsasho Degdeg ah",
    uploadBefore: "Soo rar sawirka ka hor",
    uploadAfter: "Soo rar sawirka dambe",
    takePhotoBefore: "Qaado sawir markaad gaadhiga qaadanayso",
    takePhotoAfter: "Qaado sawir markaad gaadhiga soo celinayso",
    viewSchedule: {
      en: "View Schedule",
      no: "Se Timeplan"
    },
    sendSchedule: {
      en: "Send Schedule",
      no: "Send Timeplan"
    },
    driverSchedule: {
      en: "Driver Schedule",
      no: "Sjåfør Timeplan"
    },
    scheduleFor: {
      en: "Schedule for",
      no: "Timeplan for"
    },
    totalHours: {
      en: "Total Hours",
      no: "Totale Timer"
    },
    averageHours: {
      en: "Average Hours/Day",
      no: "Gjennomsnitt Timer/Dag"
    },
    sendVia: {
      en: "Send via",
      no: "Send via"
    },
    sms: {
      en: "SMS",
      no: "SMS"
    },
    email: {
      en: "Email",
      no: "E-post"
    },
    pushNotification: {
      en: "Push Notification",
      no: "Push Varsel"
    },
    scheduleSent: {
      en: "Schedule sent successfully!",
      no: "Timeplan sendt!"
    },
    customizeMessage: {
      en: "Customize Message",
      no: "Tilpass Melding"
    },
    previewMessage: {
      en: "Preview Message",
      no: "Forhåndsvis Melding"
    },
    refresh: "Oppdater",
    refreshing: "Oppdaterer...",
    driverAuthentication: "Sjåførautentisering",
    pleaseEnterDriverDetails: "Vennligst fyll ut sjåføropplysninger for å fortsette",
    driverId: "Sjåfør ID",
    enterDriverId: "Skriv inn sjåfør ID (1234)",
    driverName: "Sjåførnavn",
    enterDriverName: "Skriv inn sjåførnavn (Bruker 1-10)",
    validating: "Validerer...",
    authenticateDriver: "Autentiser Sjåfør",
  },

  ti: {
    appTitle: "FleetTracker Pro",
    appSubtitle: "ዘመናዊ ኤሌክትሪክ መኪና ምሕደራ",
    phoneNumber: "ቁጽሪ ተሌፎን",
    phoneNumberRequired: "ቁጽሪ ተሌፎን የድሊ",
    showingResults: "ውጽኢት የርኢ",
    of: "ካብ",
    lastUpdated: "መወዳእታ ዝተሓደሰሉ ግዜ:",
    clearSearch: "ጽሬት ድሌት",
    totalFleet: "ጠቅላላ መኪናታት",
    available: "ዝርከብ",
    inUse: "ኣብ ኣጠቓቕማ",
    reserved: "ተሓዚዙ",
    maintenance: "ጽገና",
    utilization: "ኣጠቓቕማ",
    lowBatteryAlert: "ዝተሓተ ባትሪ ምጠንቀቕ",
    lowChargeAlert: "ዝተሓተ ኤሌክትሪክ ምጠንቀቕ",
    needCharging: "ምሕዳስ የድልዮ",
    needRecharging: "ምሕዳስ የድልዮ",
    vehicles: "መኪናታት",
    vehicle: "መኪና",
    thisMonth: "ኣብዚ ወርሒ",
    highUsage: "ልዑል ኣጠቓቕማ",
    mediumUsage: "ማእከላይ ኣጠቓቕማ",
    lowUsage: "ትሑት ኣጠቓቕማ",
    allStatus: "ኩሎም ኩነታት",
    allLocations: "ኩሎም ቦታታት",
    allLevels: "ኩሎም ደረጃታት",
    status: "ኩነታት",
    location: "ቦታ",
    batteryLevel: "ደረጃ ባትሪ",
    chargeLevel: "ደረጃ ኤሌክትሪክ",
    high: "ልዑል (70%+)",
    medium: "ማእከላይ (30-70%)",
    low: "ትሑት (<30%)",
    free: "ናጻ",
    busy: "ጽዑቕ",
    inTransit: "ኣብ መንገዲ",
    availableAtLastLocation: "ኣብ ናይ መወዳእታ ቦታ ዝርከብ",
    scheduledService: "ዝተመደበ ኣገልግሎት",
    take: "ውሰድ",
    return: "መለስ",
    reserve: "ሓዝ",
    manage: "ኣመሓድር",
    startTrip: "ጉዕዞ ጀምር",
    cancel: "ሰርዝ",
    close: "ዓጽ",
    takeCar: "መኪና ውሰድ",
    returnCar: "መኪና ምለስ",
    takeVehicle: "መኪና ውሰድ",
    returnVehicle: "መኪና ምለስ",
    cancelReservation: "ምሕዛዝ ሰርዝ",
    setInUse: "Sett I Bruk",
    setMaintenance: "Sett Vedlikehold",
    setAvailable: "Sett Tilgjengelig",
    deleteSelected: "Slett Valgte",
    noPhotosFound: "Ingen bilder funnet",
    justNow: "ሕጂ",
    minutesAgo: "ቅድሚ ደቓይቕ",
    hoursAgo: "ቅድሚ ሰዓታት",
    ago: "ቅድሚ",
    vehicleDetails: "ዝርዝር መኪና",
    currentlyAt: "ኣብዚ ሕጂ:",
    mileage: "ኪሎሜትር",
    miles: "ኪሎሜትር",
    battery: "ባትሪ",
    charge: "ኤሌክትሪክ",
    vehicleStatus: "ኩነታት መኪና",
    vehicleNotes: "መወከሲ መኪና",
    addNotes: "ብዛዕባ ኩነታት መኪና፣ ጸገማት፣ ጽገና ዘድልዮ ወዘተ ሓበሬታ ወስኽ።",
    currentlyInUse: "ኣብዚ ሕጂ ኣጠቓቕማ",
    reservedBy: "ዝተሓዘ ብ",
    from: "ካብ:",
    until: "ክሳብ:",
    scheduledByAdmin: "ሓዝ ኣረጋግጽ",
    reserveCar: "መኪና ሓዝ",
    confirmReservation: "ምሕዛዝ ኣረጋግጽ",
    reservationDetails: "ዝርዝር ምሕዛዝ",
    driverName: "ስም ሰዋቂ",
    reservationDate: "ዕለት ምሕዛዝ",
    startTime: "ናይ ምጅማር ግዜ",
    deliveryTime: "ናይ ምብጻሕ ግዜ (ኣማራጺ)",
    expectedDuration: "ዝተጸበየ ግዜ",
    notes: "ምልክታት (ኣማራጺ)",
    reservationSummary: "ሓጺር ምሕዛዝ",
    multipleReservations: "ብዙሕ ምሕዛዝ",
    addAnotherReservation: "ካልእ ምሕዛዝ ወስኽ",
    start: "ጀምር",
    end: "ውዳእ",
    duration: "ግዜ",
    driver: "ሰዋቂ",
    notSpecified: "ዘይተነጸረ",
    beforePhoto: "ናይ ቅድሚ ስእሊ (ምውሳድ)",
    afterPhoto: "ድሕሪ ምብጻሕ",
    uploadPhoto: "ስእሊ ኣእቱ",
    takePhoto: "ስእሊ ውሰድ",
    chooseFile: "ፋይል ምረጽ",
    remove: "ኣወግድ",
    replace: "ተክእ",
    uploadBefore: "ቅድሚ ፎቶ ኣጽዕን",
    uploadAfter: "ድሕሪ ፎቶ ኣጽዕን",
    takePhotoBefore: "መኪና ክትወስድ ከለኻ ፎቶ ርኣይ",
    takePhotoAfter: "መኪና ክትመልስ ከለኻ ፎቶ ርኣይ",
    overview: "ጠቅላላ",
    photos: "ፎቶታት",
    actions: "ተግባራት",
    required: "የድሊ",
    driverNameRequired: "ስም ሰዋቂ የድሊ",
    dateRequired: "ዕለት ምሕዛዝ የድሊ",
    timeRequired: "ግዜ ምሕዛዝ የድሊ",
    futureRequired: "ምሕዛዝ ኣብ መጻኢ ክኸውን ኣለዎ",
    fillAllFields: "በጃኹም ኩሎም ኣድላዪ ቦታታት ምልኡ",
    fixErrors: "በጃኹም ነዞም ዝስዕቡ ጌጋታት ኣርሙ:",
    overlappingReservations: "ዝተደራረቡ ምሕዛዛት ተረኺቦም",
    "1hour": "1 ሰዓት",
    "2hours": "2 ሰዓታት",
    "3hours": "3 ሰዓታት",
    "4hours": "4 ሰዓታት (ፍርቂ ዝውዕል)",
    "6hours": "6 ሰዓታት",
    "8hours": "8 ሰዓታት (ምሉእ ዝውዕል)",
    "10hours": "10 ሰዓታት",
    "12hours": "12 ሰዓታት (ዝተወሰኸ ዝውዕል)",
    "24hours": "24 ሰዓታት (ምሉእ መዓልቲ)",
    hour: "ሰዓት",
    hours: "ሰዓታት",
    halfShift: "ፍርቂ ለውጢ",
    fullShift: "ምሉእ ለውጢ",
    extendedShift: "ዝተናውሐ ለውጢ",
    fullDay: "ምሉእ መዓልቲ",
    noVehiclesFound: "ዝኾነት መኪና ኣይተረኽበትን",
    tryAdjusting: "ነቲ መርመራ ወይ ማጣሪያታት ንምምሕያሽ ፈትን",
    noVehiclesAvailable: "ኣብ መኪናኻ ዝኾነት መኪና የለን",
    startingCamera: "ካሜራ ይጅምር ኣሎ...",
    couldNotAccess: "ካሜራ ክትረክብ ኣይተኻእለን። ፍቓድካ ርኣይ።",
    retake: "እንደገና ውሰድ",
    usePhoto: "ፎቶ ተጠቐም",
    startCamera: "ካሜራ ጀምር",
    lowBatteryNeeds: "ትሑት ባትሪ - ምሕዳስ የድልዮ",
    lowChargeNeeds: "ትሑት ኤሌክትሪክ - ምሕዳስ የድልዮ",
    quickAssignment: "ቅልጡፍ ምደባ",
    uploadBefore: "ቅድሚ ፎቶ ኣጽዕን",
    uploadAfter: "ድሕሪ ፎቶ ኣጽዕን",
    takePhotoBefore: "መኪና ክትወስድ ከለኻ ፎቶ ርኣይ",
    takePhotoAfter: "መኪና ክትመልስ ከለኻ ፎቶ ርኣይ",
    viewSchedule: {
      en: "View Schedule",
      no: "Se Timeplan"
    },
    sendSchedule: {
      en: "Send Schedule",
      no: "Send Timeplan"
    },
    driverSchedule: {
      en: "Driver Schedule",
      no: "Sjåfør Timeplan"
    },
    scheduleFor: {
      en: "Schedule for",
      no: "Timeplan for"
    },
    totalHours: {
      en: "Total Hours",
      no: "Totale Timer"
    },
    averageHours: {
      en: "Average Hours/Day",
      no: "Gjennomsnitt Timer/Dag"
    },
    sendVia: {
      en: "Send via",
      no: "Send via"
    },
    sms: {
      en: "SMS",
      no: "SMS"
    },
    email: {
      en: "Email",
      no: "E-post"
    },
    pushNotification: {
      en: "Push Notification",
      no: "Push Varsel"
    },
    scheduleSent: {
      en: "Schedule sent successfully!",
      no: "Timeplan sendt!"
    },
    customizeMessage: {
      en: "Customize Message",
      no: "Tilpass Melding"
    },
    previewMessage: {
      en: "Preview Message",
      no: "Forhåndsvis Melding"
    },
    refresh: "Oppdater",
    refreshing: "Oppdaterer...",
    driverAuthentication: "Sjåførautentisering",
    pleaseEnterDriverDetails: "Vennligst fyll ut sjåføropplysninger for å fortsette",
    driverId: "Sjåfør ID",
    enterDriverId: "Skriv inn sjåfør ID (1234)",
    driverName: "Sjåførnavn",
    enterDriverName: "Skriv inn sjåførnavn (Bruker 1-10)",
    validating: "Validerer...",
    authenticateDriver: "Autentiser Sjåfør",
  },

  ar: {
    appTitle: "فليت تراكر برو",
    appSubtitle: "إدارة أسطول السيارات الكهربائية الحديثة",
    phoneNumber: "رقم الهاتف",
    phoneNumberRequired: "رقم الهاتف مطلوب",
    showingResults: "عرض النتائج",
    of: "من",
    lastUpdated: "آخر تحديث:",
    clearSearch: "مسح البحث",
    totalFleet: "إجمالي الأسطول",
    available: "متاح",
    inUse: "قيد الاستخدام",
    reserved: "محجوز",
    maintenance: "صيانة",
    utilization: "الاستخدام",
    lowBatteryAlert: "تنبيه بطارية منخفضة",
    lowChargeAlert: "تنبيه شحن منخفض",
    needCharging: "تحتاج شحن",
    needRecharging: "تحتاج إعادة شحن",
    vehicles: "مركبات",
    vehicle: "مركبة",
    thisMonth: "هذا الشهر",
    highUsage: "استخدام عالي",
    mediumUsage: "استخدام متوسط",
    lowUsage: "استخدام منخفض",
    allStatus: "جميع الحالات",
    allLocations: "جميع المواقع",
    allLevels: "جميع المستويات",
    status: "الحالة",
    location: "الموقع",
    batteryLevel: "مستوى البطارية",
    chargeLevel: "مستوى الشحن",
    high: "عالي (70% +)",
    medium: "متوسط (30-70%)",
    low: "منخفض (<30%)",
    free: "متاح",
    busy: "مشغول",
    inTransit: "في الطريق",
    availableAtLastLocation: "متاح في الموقع الأخير",
    scheduledService: "خدمة مجدولة",
    take: "أخذ",
    return: "إرجاع",
    reserve: "حجز",
    manage: "إدارة",
    startTrip: "بدء الرحلة",
    cancel: "إلغاء",
    close: "إغلاق",
    takeCar: "أخذ سيارة",
    returnCar: "إرجاع سيارة",
    takeVehicle: "أخذ مركبة",
    returnVehicle: "إرجاع مركبة",
    cancelReservation: "إلغاء الحجز",
    setInUse: "تعيين في الاستخدام",
    setMaintenance: "تعيين الصيانة",
    setAvailable: "تعيين التوفر",
    deleteSelected: "حذف المختار",
    noPhotosFound: "لم يتم العثور على صور",
    justNow: "الآن",
    minutesAgo: "منذ دقائق",
    hoursAgo: "منذ ساعات",
    ago: "منذ",
    vehicleDetails: "تفاصيل المركبة",
    currentlyAt: "حاليًا في:",
    mileage: "عدد الكيلومترات",
    miles: "كيلومتر",
    battery: "البطارية",
    charge: "الشحن",
    vehicleStatus: "حالة المركبة",
    vehicleNotes: "ملاحظات المركبة",
    addNotes: "إضافة ملاحظات حول حالة المركبة، المشاكل، احتياجات الصيانة، إلخ.",
    currentlyInUse: "قيد الاستخدام حاليًا",
    reservedBy: "محجوز بواسطة",
    from: "من:",
    until: "حتى:",
    scheduledByAdmin: "مجدول من قبل المدير",
    reserveCar: "حجز سيارة",
    confirmReservation: "تأكيد الحجز",
    reservationDetails: "تفاصيل الحجز",
    driverName: "اسم السائق",
    reservationDate: "تاريخ الحجز",
    startTime: "وقت البداية",
    deliveryTime: "وقت التسليم (اختياري)",
    expectedDuration: "المدة المتوقعة",
    notes: "ملاحظات (اختياري)",
    reservationSummary: "ملخص الحجز",
    multipleReservations: "حجوزات متعددة",
    addAnotherReservation: "إضافة حجز آخر",
    start: "ابدأ",
    end: "انتهى",
    duration: "المدة",
    driver: "سائق",
    notSpecified: "غير محدد",
    beforePhoto: "صورة قبل (الاستلام)",
    afterPhoto: "بعد التسليم",
    uploadPhoto: "رفع صورة",
    takePhoto: "التقاط صورة",
    chooseFile: "اختيار ملف",
    remove: "إزالة",
    replace: "استبدال",
    uploadBefore: "تحميل صورة قبل",
    uploadAfter: "تحميل صورة بعد",
    takePhotoBefore: "التقط صورة عند استلام السيارة",
    takePhotoAfter: "التقط صورة عند إرجاع السيارة",
    overview: "نظرة عامة",
    photos: "صور",
    actions: "إجراءات",
    required: "مطلوب",
    driverNameRequired: "اسم السائق مطلوب",
    dateRequired: "تاريخ الحجز مطلوب",
    timeRequired: "وقت الحجز مطلوب",
    futureRequired: "يجب أن يكون الحجز في المستقبل",
    fillAllFields: "يرجى ملء جميع الحقول المطلوبة",
    fixErrors: "يرجى تصحيح الأخطاء التالية:",
    overlappingReservations: "تم العثور على حجوزات متداخلة",
    "1hour": "1 ساعة",
    "2hours": "2 ساعات",
    "3hours": "3 ساعات",
    "4hours": "4 ساعات (نصف وردية)",
    "6hours": "6 ساعات",
    "8hours": "8 ساعات (وردية كاملة)",
    "10hours": "10 ساعات",
    "12hours": "12 ساعة (وردية ممتدة)",
    "24hours": "24 ساعة (يوم كامل)",
    hour: "ساعة",
    hours: "ساعات",
    halfShift: "نصف وردية",
    fullShift: "وردية كاملة",
    extendedShift: "وردية ممتدة",
    fullDay: "يوم كامل",
    noVehiclesFound: "لم يتم العثور على مركبات",
    tryAdjusting: "حاول تعديل البحث أو الفلاتر",
    noVehiclesAvailable: "لا توجد مركبات متاحة في أسطولك",
    startingCamera: "بدء تشغيل الكاميرا...",
    couldNotAccess: "تعذر الوصول إلى الكاميرا. يرجى التحقق من الأذونات.",
    retake: "إعادة الالتقاط",
    usePhoto: "استخدام الصورة",
    startCamera: "بدء الكاميرا",
    lowBatteryNeeds: "بطارية منخفضة - تحتاج إلى شحن",
    lowChargeNeeds: "شحن منخفض - يحتاج إلى إعادة شحن",
    quickAssignment: "تعيين سريع",
    uploadBefore: "تحميل صورة قبل",
    uploadAfter: "تحميل صورة بعد",
    takePhotoBefore: "التقط صورة عند استلام السيارة",
    takePhotoAfter: "التقط صورة عند إرجاع السيارة",
    viewSchedule: {
      en: "View Schedule",
      no: "Se Timeplan"
    },
    sendSchedule: {
      en: "Send Schedule",
      no: "Send Timeplan"
    },
    driverSchedule: {
      en: "Driver Schedule",
      no: "Sjåfør Timeplan"
    },
    scheduleFor: {
      en: "Schedule for",
      no: "Timeplan for"
    },
    totalHours: {
      en: "Total Hours",
      no: "Totale Timer"
    },
    averageHours: {
      en: "Average Hours/Day",
      no: "Gjennomsnitt Timer/Dag"
    },
    sendVia: {
      en: "Send via",
      no: "Send via"
    },
    sms: {
      en: "SMS",
      no: "SMS"
    },
    email: {
      en: "Email",
      no: "E-post"
    },
    pushNotification: {
      en: "Push Notification",
      no: "Push Varsel"
    },
    scheduleSent: {
      en: "Schedule sent successfully!",
      no: "Timeplan sendt!"
    },
    customizeMessage: {
      en: "Customize Message",
      no: "Tilpass Melding"
    },
    previewMessage: {
      en: "Preview Message",
      no: "Forhåndsvis Melding"
    },
    refresh: "Oppdater",
    refreshing: "Oppdaterer...",
    driverAuthentication: "Sjåførautentisering",
    pleaseEnterDriverDetails: "Vennligst fyll ut sjåføropplysninger for å fortsette",
    driverId: "Sjåfør ID",
    enterDriverId: "Skriv inn sjåfør ID (1234)",
    driverName: "Sjåførnavn",
    enterDriverName: "Skriv inn sjåførnavn (Bruker 1-10)",
    validating: "Validerer...",
    authenticateDriver: "Autentiser Sjåfør",
  },

  hi: {
    appTitle: "फ्लीट ट्रैकर प्रो",
    appSubtitle: "आधुनिक इलेक्ट्रिक फ्लीट प्रबंधन",
    phoneNumber: "फोन नंबर",
    phoneNumberRequired: "फोन नंबर आवश्यक है",
    showingResults: "परिणाम दिखा रहा है",
    of: "का",
    lastUpdated: "अंतिम अद्यतन:",
    clearSearch: "खोज साफ़ करें",
    totalFleet: "कुल फ्लीट",
    available: "उपलब्ध",
    inUse: "उपयोग में",
    reserved: "आरक्षित",
    maintenance: "रखरखाव",
    utilization: "उपयोग",
    lowBatteryAlert: "कम बैटरी अलर्ट",
    lowChargeAlert: "कम चार्ज अलर्ट",
    needCharging: "चार्जिंग की जरूरत",
    needRecharging: "रीचार्जिंग की जरूरत",
    vehicles: "वाहन",
    vehicle: "वाहन",
    thisMonth: "इस महीने",
    highUsage: "उच्च उपयोग",
    mediumUsage: "मध्यम उपयोग",
    lowUsage: "कम उपयोग",
    allStatus: "सभी स्थितियाँ",
    allLocations: "सभी स्थान",
    allLevels: "सभी स्तर",
    status: "स्थिति",
    location: "स्थान",
    batteryLevel: "बैटरी स्तर",
    chargeLevel: "चार्ज स्तर",
    high: "उच्च (70% +)",
    medium: "मध्यम (30-70%)",
    low: "कम (<30%)",
    free: "उपलब्ध",
    busy: "व्यस्त",
    inTransit: "मार्ग में",
    availableAtLastLocation: "अंतिम स्थान पर उपलब्ध",
    scheduledService: "अनुसूचित सेवा",
    take: "ले",
    return: "वापस करें",
    reserve: "आरक्षित करें",
    manage: "प्रबंधित करें",
    startTrip: "यात्रा शुरू करें",
    cancel: "रद्द करें",
    close: "बंद करें",
    takeCar: "गाड़ी लें",
    returnCar: "गाड़ी वापस करें",
    takeVehicle: "वाहन लें",
    returnVehicle: "वाहन वापस करें",
    cancelReservation: "आरक्षण रद्द करें",
    setInUse: "सेट इन यूज़",
    setMaintenance: "सेट मेंटेनन्स",
    setAvailable: "सेट उपलब्ध",
    deleteSelected: "चयनित हटाएं",
    noPhotosFound: "कोई वाहन नहीं मिला",
    justNow: "अभी",
    minutesAgo: "मिनट पहले",
    hoursAgo: "घंटे पहले",
    ago: "पहले",
    vehicleDetails: "वाहन विवरण",
    currentlyAt: "वर्तमान में:",
    mileage: "माइलेज",
    miles: "किलोमीटर",
    battery: "बैटरी",
    charge: "चार्ज",
    vehicleStatus: "वाहन स्थिति",
    vehicleNotes: "वाहन नोट्स",
    addNotes: "वाहन की स्थिति, समस्याओं, रखरखाव की जरूरतों आदि के बारे में नोट्स जोड़ें।",
    currentlyInUse: "वर्तमान में उपयोग में",
    reservedBy: "द्वारा आरक्षित",
    from: "से:",
    until: "तक:",
    scheduledByAdmin: "आरक्षण तिथि आवश्यक है",
    reserveCar: "गाड़ी आरक्षित करें",
    confirmReservation: "आरक्षण की पुष्टि करें",
    reservationDetails: "आरक्षण विवरण",
    driverName: "ड्राइवर का नाम",
    reservationDate: "आरक्षण तिथि",
    startTime: "शुरुआती समय",
    deliveryTime: "डिलीवरी समय (वैकल्पिक)",
    expectedDuration: "अपेक्षित अवधि",
    notes: "नोट्स (वैकल्पिक)",
    reservationSummary: "आरक्षण सारांश",
    multipleReservations: "कई आरक्षण",
    addAnotherReservation: "अन्य आरक्षण जोड़ें",
    start: "शुरू",
    end: "समाप्त",
    duration: "अवधि",
    driver: "ड्राइवर",
    notSpecified: "निर्दिष्ट नहीं",
    beforePhoto: "पहले की फोटो (पिकअप)",
    afterPhoto: "डिलीवरी के बाद",
    uploadPhoto: "फोटो अपलोड करें",
    takePhoto: "फोटो लें",
    chooseFile: "फ़ाइल चुनें",
    remove: "हटाएं",
    replace: "बदलें",
    uploadBefore: "पहले फोटो अपलोड करें",
    uploadAfter: "बाद में फोटो अपलोड करें",
    takePhotoBefore: "गाड़ी लेते समय फोटो लें",
    takePhotoAfter: "गाड़ी वापस करते समय फोटो लें",
    overview: "अवलोकन",
    photos: "तस्वीरें",
    actions: "क्रियाएँ",
    required: "आवश्यक",
    driverNameRequired: "ड्राइवर का नाम आवश्यक है",
    dateRequired: "आरक्षण तिथि आवश्यक है",
    timeRequired: "आरक्षण समय आवश्यक है",
    futureRequired: "आरक्षण भविष्य में होना चाहिए",
    fillAllFields: "कृपया सभी आवश्यक फ़ील्ड भरें",
    fixErrors: "कृपया निम्नलिखित त्रुटियों को ठीक करें:",
    overlappingReservations: "अतिव्यापी आरक्षण मिले",
    "1hour": "1 घंटा",
    "2hours": "2 घंटे",
    "3hours": "3 घंटे",
    "4hours": "4 घंटे (आधी शिफ्ट)",
    "6hours": "6 घंटे",
    "8hours": "8 घंटे (पूरी शिफ्ट)",
    "10hours": "10 घंटे",
    "12hours": "12 घंटे (विस्तारित शिफ्ट)",
    "24hours": "24 घंटे (पूरा दिन)",
    hour: "घंटा",
    hours: "घंटे",
    halfShift: "आधी शिफ्ट",
    fullShift: "पूरी शिफ्ट",
    extendedShift: "विस्तारित शिफ्ट",
    fullDay: "पूरा दिन",
    noVehiclesFound: "कोई वाहन नहीं मिला",
    tryAdjusting: "अपनी खोज या फ़िल्टर समायोजित करने का प्रयास करें",
    noVehiclesAvailable: "आपके फ़्लीट में कोई वाहन उपलब्ध नहीं है",
    startingCamera: "कैमरा शुरू हो रहा है...",
    couldNotAccess: "कैमरे तक नहीं पहुंच सका. कृपया अनुमतियाँ जांचें।",
    retake: "फिर से लें",
    usePhoto: "फोटो का उपयोग करें",
    startCamera: "कैमरा शुरू करें",
    lowBatteryNeeds: "कम बैटरी - चार्जिंग की जरूरत",
    lowChargeNeeds: "कम चार्ज - रीचार्जिंग की जरूरत",
    quickAssignment: "त्वरित असाइनमेंट",
    uploadBefore: "पहले फोटो अपलोड करें",
    uploadAfter: "बाद में फोटो अपलोड करें",
    takePhotoBefore: "गाड़ी लेते समय फोटो लें",
    takePhotoAfter: "गाड़ी वापस करते समय फोटो लें",
    viewSchedule: {
      en: "View Schedule",
      no: "Se Timeplan"
    },
    sendSchedule: {
      en: "Send Schedule",
      no: "Send Timeplan"
    },
    driverSchedule: {
      en: "Driver Schedule",
      no: "Sjåfør Timeplan"
    },
    scheduleFor: {
      en: "Schedule for",
      no: "Timeplan for"
    },
    totalHours: {
      en: "Total Hours",
      no: "Totale Timer"
    },
    averageHours: {
      en: "Average Hours/Day",
      no: "Gjennomsnitt Timer/Dag"
    },
    sendVia: {
      en: "Send via",
      no: "Send via"
    },
    sms: {
      en: "SMS",
      no: "SMS"
    },
    email: {
      en: "Email",
      no: "E-post"
    },
    pushNotification: {
      en: "Push Notification",
      no: "Push Varsel"
    },
    scheduleSent: {
      en: "Schedule sent successfully!",
      no: "Timeplan sendt!"
    },
    customizeMessage: {
      en: "Customize Message",
      no: "Tilpass Melding"
    },
    previewMessage: {
      en: "Preview Message",
      no: "Forhåndsvis Melding"
    },
    refresh: "Oppdater",
    refreshing: "Oppdaterer...",
    driverAuthentication: "Sjåførautentisering",
    pleaseEnterDriverDetails: "Vennligst fyll ut sjåføropplysninger for å fortsette",
    driverId: "Sjåfør ID",
    enterDriverId: "Skriv inn sjåfør ID (1234)",
    driverName: "Sjåførnavn",
    enterDriverName: "Skriv inn sjåførnavn (Bruker 1-10)",
    validating: "Validerer...",
    authenticateDriver: "Autentiser Sjåfør",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("no")

  const t = (key: string): string => {
    const translation = translations[language]?.[key] || translations.en?.[key] || key
    return typeof translation === 'string' ? translation : key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
